# HTTP 连接配置 TODO
ok:
  http:
    connect-timeout: 30
    keep-alive-duration: 300
    max-idle-connections: 200
    read-timeout: 30
    write-timeout: 30

# 腾讯云账号相关的信息配置 TODO
tencent:
  sms:
    account:
      secret-id: AKID1C8oDLCo9D3dwynLegRv96mAI9j23oIV
      secret-key: yg7HAm7AwRgeMmwoPjnZ4VgbFchW4LL3
      sign_name: monsterIT公众号
      sms-sdk-app-id: 1400618277
      template-id: 1263085
